### ISSUE TITLE
Add support to resolve a URL

### ISSUE THREAD

**Issue by JeffResc** [AlphaT3ch/is.gd#4]
Add support to resolve a URL. This function should allow the user to input a Is.gd and return the expanded form of that URL. [Here's an example of how it's done in Python](https://taoofmac.com/space/blog/2009/08/10/2205), but it will need to be ported to JavaScript/Node.js for this project. Please reply if you'd like to be assigned to this issue.

**Comment by gillianomenezes** [comment]
Hello! May I solve this issue?

**Comment by JeffResc** [comment]
@gillianomenezes Sounds good!

**Comment by JeffResc** [comment]
For anyone else looking to participate in Hacktoberfest, [this issue](https://github.com/JeffResc/V.gd-Node.js/issues/8) is similar and open still.

**Comment by gillianomenezes** [comment]
@JeffResc the CI is failing and I have no idea why... Could you help me?
